config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get  '/hashtag',      to: 'hashtag#index',     as: 'hashtag'
  post '/hashtag',      to: 'hashtag#search',    as: 'search_hashtag'
  post '/hashtag',      to: 'hashtag#mark',      as: 'mark_hashtag'
  get  '/hashtag/read', to: 'hashtag#view_read', as: 'view_read'

  root to: 'hashtag#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hashtag_controller.rb
class HashtagController < ApplicationController
  def index
    @hashtag_posts = []
  end

  def mark
    Hashtag.tap.new do |hashtag|
      hashtag.hashtag_id = params[:id]
      hashtag.message    = params[:message]
    end
  end

  def view_read
    @hashtag_posts = Hashtag.all
  end

  def search
    hashtag_id     = HashtagService.search_hashtag(params[:search_term])
    @hashtag_posts = HashtagService.search_hashtag_posts(hashtag_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hashtag/index.html.erb
<h1>Instagram hashtag search app </h1>

<%= form_tag(search_hashtag_path) do %>
  <%= text_field_tag :search_term %>
  <%= submit_tag 'Search' %>
<% end %>

<h1>Hashtags</h1>
<%= link_to 'View read posts', view_read_path %>
<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <% @hashtag_posts.each do |post_id| %>
        <% post = HashtagService.get_post_with_hashtag(post_id) %>
        <div>
            <strong> <%= post_id["id"] %></strong>
            <strong> <%= post_id["message"] %></strong>
            <%= link_to 'Mark as read', mark_hashtag_path(post) %>
        </div>
      <% end %>
     </tr>
  </tbody>
</table>

app/views/hashtag/view_read.html.erb
<h1>Saved Hashtag posts</h1>
<%= link_to 'Back to search', hashtag_path %>
<br><br>
<table>
  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <% @hashtag_posts.each do |post| %>
        <div>
            <strong> <%= post.id %></strong>
            <strong> <%= post.message %></strong>
            <%= link_to 'delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      <% end %>
     </tr>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hashtagsearchapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>